import type { CovpagesData, FileCoverage, CoverageMetric } from '../types.js';

export interface CovpagesProps {
  /**
   * Complete coverage dataset generated by covpages CLI or aggregator
   */
  data?: CovpagesData | null;
  /**
   * URL to dynamically fetch covpages-data.json or history.json
   */
  dataUrl?: string;
  /**
   * Initial active tab
   * @default 'files'
   */
  initialTab?: 'files' | 'trends' | 'commits';
  /**
   * Theme mode: 'light' | 'dark' | 'auto'
   * @default 'auto'
   */
  theme?: 'light' | 'dark' | 'auto';
  /**
   * Custom base path for routing (e.g. '/covpages/')
   * @default '/'
   */
  basePath?: string;
  /**
   * Optional custom CSS class name for container
   */
  className?: string;
  /**
   * Callback when active file changes
   */
  onFileSelect?: (filePath: string) => void;
  /**
   * Callback when active branch/ref changes
   */
  onRefChange?: (refType: 'branch' | 'tag', refName: string) => void;
}

export interface CovpagesContextValue {
  data: CovpagesData | null;
  activeTab: 'files' | 'trends' | 'commits';
  currentFolder: string;
  selectedFile: string | null;
  activeRefType: 'branch' | 'tag';
  activeRefName: string;
  theme: 'light' | 'dark' | 'auto';
  sidebarVisible: boolean;
  filterText: string;
  sortColumn: 'name' | 'lines' | 'functions' | 'branches';
  sortAsc: boolean;
  setActiveTab: (tab: 'files' | 'trends' | 'commits') => void;
  setCurrentFolder: (folder: string) => void;
  setSelectedFile: (file: string | null) => void;
  setActiveRef: (type: 'branch' | 'tag', name: string) => void;
  setTheme: (theme: 'light' | 'dark' | 'auto') => void;
  toggleSidebar: () => void;
  setFilterText: (text: string) => void;
  setSort: (col: 'name' | 'lines' | 'functions' | 'branches') => void;
}
